WebApplication/Controllers/CompareController.cs
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class CompareController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication/Controllers/DefaultController.cs
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Marcin Trendel">

    <title>@ViewBag.Title</title>
    
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.flot.min.js"></script>
    <script src="~/Scripts/jquery.flot.time.min.js"></script>
    <script src="~/Scripts/jquery.flot.selection.min.js"></script>
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.min.js"></script>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    
</head>
<body>
    <div id="loadingPage"></div>
    <div id="warnings" class="white_content">
        <h1>Błędy:</h1>
        <p id="warning_container">This text block is vertically centered.</p>
    </div>
    <div id="fade" class="black_overlay"></div>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Strona główna", "Index", "Default", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Porównaj", "Index", "Compare", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year MT</p>
        </footer>
    </div>

    

</body>
</html>